// src/data/indiaLocations.js

// Master data
const locations = {
  India: {
    "Andaman and Nicobar": ["Port Blair", "South Andaman", "Bamboo Flat", "Nicobar"],
    "Andhra Pradesh": [
      "Adoni",
      "Suluru",
      "Srisailain",
      "Vadlapudi",
      "Vadlamuru",
      "Venkatagiri",
      "Vepagunta",
      "Vinukonda",
      "Vijayawada",
      "Vizianagaram",
      "Vizianagaram District",
      "Visakhapatnam",
      "Vuyyuru",
      "Yanam",
      "Yanamalakuduru",
      "West Godavari",
      "pedda nakkalapalem",
      "Uravakonda",
      "Yarada"
    ],
    "Arunachal Pradesh": [
      "Anjaw",
      "Along",
      "Basar",
      "Bomdila",
      "Changlang",
      "Dibang Valley",
      "East Kameng",
      "East Siang",
      "Hayuliang",
      "Itanagar",
      "Khonsa",
      "Kurung Kumey",
      "Lower Dibang Valley",
      "Lower Subansiri",
      "Lohit District",
      "Margherita",
      "Naharlagun",
      "Tawang",
      "Tezu",
      "Tirap",
      "Ziro"
    ],
    Assam: [
      "Dhubri",
      "Dibrugarh",
      "Dima Hasao District",
      "Digboi",
      "Guwahati",
      "Raha",
      "Rangapara",
      "Rangia",
      "Sarupathar",
      "Sibsagar",
      "Silapathar",
      "Silchar",
      "Sapatgram",
      "Sonari",
      "Sonitpur",
      "Soalkuchi",
      "Sorbhog",
      "Tinsukia",
      "Tezpur",
      "Titabar",
      "Udalguri"
    ],
    Bihar: [
      "Gaya",
      "Luckeesarai",
      "Madhubani",
      "Madhepura",
      "Maharajgani",
      "Mairwa",
      "Mithila",
      "Mokameh",
      "Munger",
      "Muzaffarpur",
      "Mohiuddi Nagar",
      "Mothihari",
      "Nalanda",
      "Nasriganj",
      "Nabinagar",
      "Naugachhia",
      "Nawada",
      "Nirmali",
      "Patna",
      "Lakhisarai",
      "Lalganj"
    ],
    Chandigarh: ["Chandigarh"],
    "Dadra and Nagar Haveli and Daman and Diu": [
      "Amli",
      "Dadra",
      "Dadra & Nagar Haveli",
      "Daman",
      "Diu",
      "Silvassa"
    ],
    Delhi: [
      "Alipur",
      "Bawana",
      "Central Delhi",
      "Deoli",
      "Dwarka",
      "East Delhi",
      "Karol Bagh",
      "Najafgarh",
      "Nangloi Jat",
      "Narela",
      "New Delhi",
      "North Delhi",
      "North East Delhi",
      "North West Delhi",
      "Pitampura",
      "Rohini",
      "Saket",
      "South Delhi",
      "South West Delhi",
      "West Delhi"
    ],
    Goa: [
      "Margao",
      "North Goa",
      "Panaji",
      "Pernem",
      "Ponda",
      "Quepem",
      "Queula",
      "Raia",
      "Saligao",
      "Sancoale",
      "Sanquelim",
      "Sanvordem",
      "Sanguem",
      "Serula",
      "Solim",
      "South Goa",
      "Taleigao",
      "Vagator",
      "Valpoy",
      "Varca",
      "Vasco da Gama"
    ],
    Gujarat: [
      "Ahmedabad",
      "Lakhtar",
      "Lalpur",
      "Limbdi",
      "Lathi",
      "Mandal",
      "Malpur",
      "Mansa",
      "Manavadar",
      "Mandvi",
      "Mangrol",
      "Nadiad",
      "Naliya",
      "Naroda",
      "Narmada",
      "Navsari",
      "Okha",
      "Olpad",
      "Padra",
      "Paddhari",
      "Surat",
      "Vadodara"
    ],
    Haryana: [
      "Asandh",
      "Faridabad",
      "Gurugram",
      "Panipat",
      "Punahana",
      "Pundri",
      "Rania",
      "Ratia",
      "Rewari",
      "Rohtak",
      "Safidon",
      "Samalkha",
      "Shadipur Julana",
      "Shahabad",
      "Sirsa",
      "Sohna",
      "Sonipat",
      "Taoru",
      "Thanesar",
      "Tohana",
      "Tosham",
      "Uklana",
      "Yamunanagar"
    ],
    "Himachal Pradesh": [
      "Dharamshala",
      "Jogindarnagar",
      "Jubbal",
      "Jutogh",
      "Kalka",
      "Kangra",
      "Kangar",
      "Kinnaur",
      "Kasauli",
      "Kotkhai",
      "Kotla",
      "Kyelang",
      "Lahul and Spiti",
      "Manali",
      "Mandi",
      "Nahan",
      "Nalagarh",
      "Nadaun",
      "Nagar",
      "Shimla",
      "Jawala Mukhi"
    ],
    "Jammu and Kashmir": [
      "Anantnag",
      "Jammu",
      "Pattan",
      "Parol",
      "Punch",
      "Pulwama",
      "Qazigund",
      "Rajaori",
      "Ramban",
      "Ramgarh",
      "Ramnagar",
      "Rajauri",
      "Riasi",
      "Samba",
      "Shupiyan",
      "Sopur",
      "Thanna Mandi",
      "Thang",
      "Tral",
      "Tsrar Sharif",
      "Udhampur",
      "Uri",
      "Srinagar"
    ],
    Jharkhand: [
      "Chatra",
      "Dhanbad",
      "Dhanwar",
      "Deogarh",
      "Dugda",
      "Patamda",
      "Pathardih",
      "Pashchim Singhbhum",
      "Purba Singhbhum",
      "Ramgarh",
      "Ranchi",
      "Ray",
      "Sahibganj",
      "Saraikela",
      "Sijua",
      "Simdega",
      "Sini",
      "Topchanchi"
    ],
    Karnataka: [
      "Bangalore",
      "Magadi",
      "Madikeri",
      "Maddagiri",
      "Maddur",
      "Mahalingpur",
      "Malavalli",
      "Malur",
      "Manvi",
      "Mulki",
      "Mudbidri",
      "Mayakonda",
      "Mysore",
      "Mysuru",
      "Nagara",
      "Nanjangud",
      "Navalgund",
      "Narasimharajapura",
      "Naregal",
      "Nargund",
      "Nelamangala",
      "Nagamangala",
      "Nyamti",
      "Hubli"
    ],
    Kerala: [
      "Kochi",
      "Kozhikode",
      "Mahe",
      "Malappuram",
      "Mallettupuzha",
      "Mannanur",
      "Muvattupula",
      "Muvattupuzha",
      "Mavelikara",
      "Munnar",
      "Muluppilagadu",
      "Marayur",
      "Naduvannur",
      "Nadapuram",
      "Neyyattinkara",
      "Nileshwar",
      "Ottappalam",
      "Panamaram",
      "Palackattumala",
      "Palakkad District",
      "Pune"
    ],
    Lakshadweep: ["Kavaratti"],
    Maharashtra: [
      "Ashta",
      "Badlapur",
      "Balapur",
      "Bandra",
      "Baramati",
      "Barsi",
      "Beed",
      "Bhiwandi",
      "Bhoom",
      "Bhusaval",
      "Biloli",
      "Boisar",
      "Buldana",
      "Bhigvan",
      "Bhayandar",
      "Bhor",
      "Bhudgaon",
      "Chandrapur",
      "Mumbai",
      "Nagpur",
      "Pune"
    ],
    "Madhya Pradesh": [
      "Bhopal",
      "Gwalior",
      "Indore",
      "Machalpur",
      "Mandleshwar",
      "Manpur",
      "Nagda",
      "Nagod",
      "Naigarhi",
      "Nainpur",
      "Neemuch",
      "Nepanagar",
      "Naraini",
      "Narayangarh",
      "Nasrullahganj",
      "Narsimhapur",
      "Narsinghgarh",
      "Narwar",
      "Nasrullahganj",
      "Orchha",
      "Palera",
      "Pachmarhi",
      "Panara"
    ],
    Manipur: [
      "Chandel",
      "Churachandpur",
      "Imphal",
      "Imphal East",
      "Imphal West",
      "Jiribam",
      "Kakching",
      "Kamjong",
      "Kangpokpi",
      "Noney",
      "Pherzawl",
      "Senapati",
      "Tamenglong",
      "Tengnoupal",
      "Thoubal",
      "Ukhrul",
      "Bishnupur"
    ],
    Meghalaya: [
      "Cherrapunji",
      "East Garo Hills",
      "East Jaintia Hills",
      "East Khasi Hills",
      "Mairang",
      "Mankachar",
      "Nongpoh",
      "Nongstoin",
      "North Garo Hills",
      "Ri-Bhoi",
      "Shillong",
      "South Garo Hills",
      "South West Garo Hills",
      "South West Khasi Hills",
      "Tura",
      "West Garo Hills",
      "West Jaintia Hills",
      "West Khasi Hills"
    ],
    Mizoram: [
      "Aizawl",
      "Champhai",
      "Darlawn",
      "Khawhai",
      "Kolasib",
      "Lawngtlai",
      "Lunglei",
      "Mamit",
      "North Vanlaiphai",
      "Saiha",
      "Saitlaw",
      "Sairang",
      "Serchhip",
      "Thenzawl"
    ],
    Nagaland: [
      "Dimapur",
      "Kohima",
      "Mokokchung",
      "Mon",
      "Peren",
      "Phek",
      "Tuensang",
      "Tuensang District",
      "Wokha",
      "Zunheboto"
    ],
    Orissa: [
      "Asika",
      "Athagarh",
      "Bhubaneswar",
      "Cuttack",
      "Puri",
      "Purushottampur",
      "Rambha",
      "Rayagada",
      "Remuna",
      "Raurkela",
      "Rengali",
      "Sambalpur",
      "Sonepur",
      "Soro",
      "Subarnapur",
      "Sundargarh",
      "Talcher",
      "Tarabha",
      "Titlagarh",
      "Udayagiri"
    ],
    Puducherry: ["Yanam", "Puducherry", "Mahe", "Karaikal"],
    Punjab: [
      "Amritsar",
      "Bholath",
      "Dhudi",
      "Dera Bassi",
      "Ishanpur",
      "Jalandhar",
      "Ludhiana",
      "Raikot",
      "Rajpura",
      "Rajasansi",
      "Rahon",
      "Rupnagar",
      "Sardulgarh",
      "Shahid Bhagat Singh Nagar",
      "Shahkot",
      "Sham Churasi",
      "Sirhind-Fategarh",
      "Sultanpur Lodhi",
      "Sunam",
      "Talwandi Bhai",
      "Talwara",
      "Tarn Taran Sahib",
      "Zira"
    ],
    Rajasthan: [
      "Jaipur",
      "Jaisalmer",
      "Jalor",
      "Jalore",
      "Jahazpur",
      "Jaitaran",
      "Kanor",
      "Kaman",
      "Kapren",
      "Kishangarh",
      "Khanpur",
      "Kekri",
      "Keshorai Patan",
      "Khetri",
      "Kotputli",
      "Kuchaman",
      "Kuchera",
      "Kota",
      "Khandela",
      "Udaipur"
    ],
    Sikkim: [
      "East District",
      "Gangtok",
      "Gyalshing",
      "Mangan",
      "Namchi",
      "North District",
      "Naya Bazar",
      "Rangpo",
      "Singtam",
      "South District",
      "West District",
      "Jorethang",
      "Pelling"
    ],
    "Tamil Nadu": [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Namagiripettai",
      "Nagercoil",
      "Needamangalam",
      "Neelankarai",
      "Negapatam",
      "Nilakottai",
      "Nilgiris",
      "Nellikkuppam",
      "Nattarasankottai",
      "Naravarikuppam",
      "Omalur",
      "Ooty",
      "Odugattur",
      "Palladam",
      "Pallappatti",
      "Pallattur",
      "Pallikondai",
      "Pallipattu",
      "Pallippatti",
      "Pallavaram",
      "Tamil Nadu"
    ],
    Telangana: [
      "Hyderabad",
      "Jagtial",
      "Jangaon",
      "Jayashankar Bhupalapally",
      "Jogulamba Gadwal",
      "Kamareddy",
      "Kamareddi",
      "Karimnagar",
      "Kagaznagar",
      "Kakathampalle",
      "Khammam",
      "Kodapet",
      "Kodatapalli",
      "Koratal",
      "Kothapet",
      "Mahabubabad",
      "Mahbubnagar",
      "Mancheral",
      "Mandamarri",
      "Nizamabad",
      "Warangal"
    ],
    Tripura: [
      "Agartala",
      "Ambasa",
      "Amarpur",
      "Barjala",
      "Belonia",
      "Dharmanagar",
      "Dhalai",
      "Gomati",
      "Kailashahar",
      "Khowai",
      "North Tripura",
      "Ranir Bazar",
      "Sabrum",
      "South Tripura",
      "Sonamura",
      "Tripura",
      "Unakoti",
      "Udaipur",
      "West Tripura"
    ],
    Uttarakhand: [
      "Clement Town",
      "Dehradun",
      "Dharchula",
      "Doiwala",
      "Dugadda",
      "Dwarahat",
      "Haridwar",
      "Joshimath",
      "Kalagarh Project Colony",
      "Kaladhungi",
      "Kashipur",
      "Khatima",
      "Kichha",
      "Kotdwara",
      "Lansdowne",
      "Laksar",
      "Lohaghat",
      "Manglaur",
      "Mussoorie",
      "Naini Tal",
      "Nainital",
      "Narendranagar",
      "Rupnagar"
    ],
    "Uttar Pradesh": [
      "Jyotiba Phule Nagar",
      "Jalaun",
      "Jansath",
      "Jhansi",
      "Jhinjhak",
      "Jhusi",
      "Kabrai",
      "Kadaura",
      "Kaimganj",
      "Kaithwa",
      "Kanpur",
      "Kanpur Dehat",
      "Kannauj",
      "Kamalganj",
      "Kairana",
      "Karari",
      "Karhal",
      "Katra",
      "Kaushambi",
      "Lucknow",
      "Varanasi"
    ],
    Chhattisgarh: [
      "Dantewada",
      "Pathalgaon",
      "Pendra",
      "Pandaria",
      "Pasan",
      "Pithora",
      "Pandatarai",
      "Patan",
      "Raipur",
      "Raigarh",
      "Ratanpur",
      "Seorinarayan",
      "Simga",
      "Raj Nandgaon",
      "Ramanuj Ganj",
      "Saraipali",
      "Sakti",
      "Surguja",
      "Umar Kot",
      "Uttar Bastar Kanker"
    ],
    Ladakh: ["Leh", "Kargil"],
    "West Bengal": [
      "Ahmedpur",
      "Aistala",
      "Aknapur",
      "Alipurduar",
      "Amta",
      "Amtala",
      "Andal",
      "Arambagh community development block",
      "Asansol",
      "Ashoknagar Kalyangarh",
      "Badkulla",
      "Baduria",
      "Bagdogra",
      "Bagnan",
      "Bagula",
      "Bahula",
      "Baidyabati",
      "Bakreswar",
      "Balarampur",
      "Bally",
      "Darjeeling",
      "Kolkata",
      "Siliguri"
    ]
  }
};

// --- Helpers ---

/** Get all states/UTs under India */
export const getStates = () => Object.keys(locations.India);

/** Get cities for a given state/UT (safe if state not found) */
export const getCities = (StateCode) => locations.India[StateCode] ?? [];

/** Full data export */
export default locations;
